url: https://vvitohu.github.io
baseurl: 
# Site settings
title: Dev Diaries
email: otis.vito@gmail.com
description: "胡勝紘的個人作品集與技術筆記"


header_img:
- header-bg.jpg
- header-bg.jpg
- header-bg.jpg

# Team names, titles and social links
people:
- name: 胡勝紘
  pic: 1
  position: 
  social:
    - title: instagram
      url: https://www.instagram.com/otis.vito/
    - title: facebook
      url: #
    - title: github
      url: https://github.com/vvitohu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/otis.vito/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/vvitohu

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty

collections:
  courses:
    output: true
    permalink: /courses/:path/